config/routes.rb
A4nt::Engine.routes.draw do
  resources :announcements

  root to: "announcements#index"
end

app/models/a4nt/announcement.rb
module A4nt
  class Announcement < ActiveRecord::Base
    module Target
      ALL = 'all'
      NON_MEMBER = 'nonmember'
      MEMBER = 'member'

      def self.all
        self.constants.map { |name| self.const_get(name) }
      end
    end

    validates :title, :body, :start_time, :end_time, :position, :target, presence: true
    validates :target, inclusion: { in: Target.all }

    scope :active, -> { where(["start_time <= ? AND end_time >= ?", Time.now, Time.now]) }
    scope :newer, -> { active.order('position ASC') }
    scope :non_members, -> { newer.where(target: [ Target::ALL, Target::NON_MEMBER ]) }
    scope :members, -> { newer.where(target: [ Target::ALL, Target::MEMBER ]) }
  end
end

app/controllers/a4nt/announcements_controller.rb
require_dependency "a4nt/application_controller"

module A4nt
  class AnnouncementsController < ApplicationController
    # GET /announcements
    # GET /announcements.json
    def index
      @announcements = Announcement.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @announcements }
      end
    end
  
    # GET /announcements/1
    # GET /announcements/1.json
    def show
      @announcement = Announcement.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @announcement }
      end
    end
  
    # GET /announcements/new
    # GET /announcements/new.json
    def new
      @announcement = Announcement.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @announcement }
      end
    end
  
    # GET /announcements/1/edit
    def edit
      @announcement = Announcement.find(params[:id])
    end
  
    # POST /announcements
    # POST /announcements.json
    def create
      @announcement = Announcement.new(announcement_params)
  
      respond_to do |format|
        if @announcement.save
          format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
          format.json { render json: @announcement, status: :created, location: @announcement }
        else
          format.html { render action: "new" }
          format.json { render json: @announcement.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /announcements/1
    # PUT /announcements/1.json
    def update
      @announcement = Announcement.find(params[:id])
  
      respond_to do |format|
        if @announcement.update_attributes(announcement_params)
          format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @announcement.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /announcements/1
    # DELETE /announcements/1.json
    def destroy
      @announcement = Announcement.find(params[:id])
      @announcement.destroy
  
      respond_to do |format|
        format.html { redirect_to announcements_url }
        format.json { head :no_content }
      end
    end

    private

      def announcement_params
        params.require(:announcement).permit(:body, :end_time, :position, :start_time, :title, :target)
      end
  end
end

app/controllers/a4nt/application_controller.rb
module A4nt
  class ApplicationController < ActionController::Base
  end
end

app/helpers/a4nt/announcements_helper.rb
module A4nt
  module AnnouncementsHelper
  end
end

app/helpers/a4nt/application_helper.rb
module A4nt
  module ApplicationHelper
  end
end

app/views/a4nt/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :target %><br />
    <%= f.select :target, A4nt::Announcement::Target.all %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/a4nt/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/a4nt/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Position</th>
    <th>Target</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @announcements.each do |announcement| %>
  <tr>
    <td><%= announcement.title %></td>
    <td><%= announcement.body %></td>
    <td><%= announcement.start_time %></td>
    <td><%= announcement.end_time %></td>
    <td><%= announcement.position %></td>
    <td><%= announcement.target %></td>
    <td><%= link_to 'Show', announcement %></td>
    <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
    <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Announcement', new_announcement_path %>

app/views/a4nt/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/a4nt/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @announcement.title %>
</p>

<p>
  <b>Body:</b>
  <%= @announcement.body %>
</p>

<p>
  <b>Start time:</b>
  <%= @announcement.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @announcement.end_time %>
</p>

<p>
  <b>Position:</b>
  <%= @announcement.position %>
</p>

<p>
  <b>Target:</b>
  <%= @announcement.target %>
</p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/layouts/a4nt/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A4nt</title>
  <%= stylesheet_link_tag    "a4nt/application", :media => "all" %>
  <%= javascript_include_tag "a4nt/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>